"""Add_MaquinaExcelMap

Revision ID: 11abafda09a3
Revises: 57ccd41a077e
Create Date: 2025-12-08 23:30:53.802929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11abafda09a3'
down_revision = '57ccd41a077e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquina_excel_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('excel_nombre', sa.String(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=True),
    sa.Column('puesto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['puesto_id'], ['puesto.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salon_id', 'excel_nombre', name='uq_excel_map_salon_nombre')
    )
    op.create_index(op.f('ix_maquina_excel_map_id'), 'maquina_excel_map', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maquina_excel_map_id'), table_name='maquina_excel_map')
    op.drop_table('maquina_excel_map')
    # ### end Alembic commands ###
