"""Add_RecaudacionFichero

Revision ID: 57ccd41a077e
Revises: 6a1c0f531cc8
Create Date: 2025-12-08 20:24:09.125421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ccd41a077e'
down_revision = '6a1c0f531cc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recaudacion_fichero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recaudacion_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recaudacion_id'], ['recaudacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recaudacion_fichero_id'), 'recaudacion_fichero', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recaudacion_fichero_id'), table_name='recaudacion_fichero')
    op.drop_table('recaudacion_fichero')
    # ### end Alembic commands ###
