"""refactor_machines_final

Revision ID: 6a1c0f531cc8
Revises: cd90a212c6ec
Create Date: 2025-12-07 12:48:24.238851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1c0f531cc8'
down_revision = 'cd90a212c6ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo_maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cantidad_puestos', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_maquina_id'), 'grupo_maquina', ['id'], unique=False)
    op.create_index(op.f('ix_grupo_maquina_nombre'), 'grupo_maquina', ['nombre'], unique=False)
    
    op.add_column('maquina', sa.Column('grupo_id', sa.Integer(), nullable=True))
    # Step 1: Add new columns as nullable
    op.add_column('maquina', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('maquina', sa.Column('nombre_referencia_uorsa', sa.String(), nullable=True))
    op.add_column('maquina', sa.Column('es_multipuesto', sa.Boolean(), nullable=True))
    op.add_column('maquina', sa.Column('observaciones', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'maquina', 'grupo_maquina', ['grupo_id'], ['id'])
    
    # Step 2: Backfill data
    op.execute("UPDATE maquina SET nombre = COALESCE(numero_serie, 'MQ-' || CAST(id AS VARCHAR))")

    # Step 3: Enforce NOT NULL
    op.alter_column('maquina', 'nombre', nullable=False)

    op.add_column('tipo_maquina', sa.Column('tasa_semanal_orientativa', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tipo_maquina', sa.Column('es_multipuesto', sa.Boolean(), nullable=True))
    
    # Step 4: Backfill Type Data
    op.execute("UPDATE tipo_maquina SET tasa_semanal_orientativa = tasa_semanal_base")

    # Step 5: Enforce NOT NULL
    op.alter_column('tipo_maquina', 'tasa_semanal_orientativa', nullable=False)

    op.drop_column('tipo_maquina', 'tasa_semanal_base')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_maquina', sa.Column('tasa_semanal_base', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('tipo_maquina', 'es_multipuesto')
    op.drop_column('tipo_maquina', 'tasa_semanal_orientativa')
    op.drop_constraint(None, 'maquina', type_='foreignkey')
    op.drop_column('maquina', 'observaciones')
    op.drop_column('maquina', 'es_multipuesto')
    op.drop_column('maquina', 'nombre_referencia_uorsa')
    op.drop_column('maquina', 'nombre')
    op.drop_column('maquina', 'grupo_id')
    op.drop_index(op.f('ix_grupo_maquina_nombre'), table_name='grupo_maquina')
    op.drop_index(op.f('ix_grupo_maquina_id'), table_name='grupo_maquina')
    op.drop_table('grupo_maquina')
    # ### end Alembic commands ###
