"""Initial_migration

Revision ID: cd90a212c6ec
Revises: 
Create Date: 2025-12-05 20:42:37.597320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd90a212c6ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permiso_codigo'), 'permiso', ['codigo'], unique=True)
    op.create_index(op.f('ix_permiso_id'), 'permiso', ['id'], unique=False)
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_codigo'), 'rol', ['codigo'], unique=True)
    op.create_index(op.f('ix_rol_id'), 'rol', ['id'], unique=False)
    op.create_table('salon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salon_codigo'), 'salon', ['codigo'], unique=True)
    op.create_index(op.f('ix_salon_id'), 'salon', ['id'], unique=False)
    op.create_table('tipo_concepto_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('signo_por_defecto', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tipo_maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('tasa_semanal_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tasa_por_puesto', sa.Boolean(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_tipo_maquina_id'), 'tipo_maquina', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    op.create_table('maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('tipo_maquina_id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(), nullable=False),
    sa.Column('numero_serie', sa.String(), nullable=True),
    sa.Column('maquina_padre_id', sa.Integer(), nullable=True),
    sa.Column('numero_puesto', sa.Integer(), nullable=True),
    sa.Column('tasa_semanal_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_alta', sa.Date(), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['maquina_padre_id'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ),
    sa.ForeignKeyConstraint(['tipo_maquina_id'], ['tipo_maquina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maquina_id'), 'maquina', ['id'], unique=False)
    op.create_table('recaudacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=False),
    sa.Column('etiqueta', sa.String(), nullable=True),
    sa.Column('origen', sa.String(), nullable=True),
    sa.Column('referencia_fichero', sa.String(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recaudacion_id'), 'recaudacion', ['id'], unique=False)
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('usuario_rol',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('usuario_salon',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('puede_ver', sa.Boolean(), nullable=True),
    sa.Column('puede_editar', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['salon_id'], ['salon.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'salon_id')
    )
    op.create_table('recaudacion_concepto_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recaudacion_id', sa.Integer(), nullable=True),
    sa.Column('maquina_id', sa.Integer(), nullable=True),
    sa.Column('tipo_concepto_extra_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['recaudacion_id'], ['recaudacion.id'], ),
    sa.ForeignKeyConstraint(['tipo_concepto_extra_id'], ['tipo_concepto_extra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recaudacion_maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recaudacion_id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('retirada_efectivo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cajon', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pago_manual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tasa_calculada', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tasa_ajuste', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tasa_final', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('detalle_tasa', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['recaudacion_id'], ['recaudacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recaudacion_id', 'maquina_id', name='uq_recaudacion_maquina')
    )
    op.create_index(op.f('ix_recaudacion_maquina_id'), 'recaudacion_maquina', ['id'], unique=False)
    op.create_table('usuario_maquina',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('puede_ver', sa.Boolean(), nullable=True),
    sa.Column('puede_editar', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'maquina_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_maquina')
    op.drop_index(op.f('ix_recaudacion_maquina_id'), table_name='recaudacion_maquina')
    op.drop_table('recaudacion_maquina')
    op.drop_table('recaudacion_concepto_extra')
    op.drop_table('usuario_salon')
    op.drop_table('usuario_rol')
    op.drop_table('rol_permiso')
    op.drop_index(op.f('ix_recaudacion_id'), table_name='recaudacion')
    op.drop_table('recaudacion')
    op.drop_index(op.f('ix_maquina_id'), table_name='maquina')
    op.drop_table('maquina')
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tipo_maquina_id'), table_name='tipo_maquina')
    op.drop_table('tipo_maquina')
    op.drop_table('tipo_concepto_extra')
    op.drop_index(op.f('ix_salon_id'), table_name='salon')
    op.drop_index(op.f('ix_salon_codigo'), table_name='salon')
    op.drop_table('salon')
    op.drop_index(op.f('ix_rol_id'), table_name='rol')
    op.drop_index(op.f('ix_rol_codigo'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_permiso_id'), table_name='permiso')
    op.drop_index(op.f('ix_permiso_codigo'), table_name='permiso')
    op.drop_table('permiso')
    # ### end Alembic commands ###
