"""add bloqueada to recaudacion

Revision ID: cefbbb8f358e
Revises: 11abafda09a3
Create Date: 2025-12-11 22:31:34.572287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cefbbb8f358e'
down_revision = '11abafda09a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recaudacion', sa.Column('bloqueada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recaudacion', 'bloqueada')
    # ### end Alembic commands ###
